-- Create the memories table
create table memories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  content text,
  media_url text,
  media_type text, -- 'image' | 'video' | 'audio'
  latitude double precision not null,
  longitude double precision not null,
  location_name text,
  memory_date timestamp with time zone,
  is_public boolean default false
);

-- Set up Row Level Security (RLS)
alter table memories enable row level security;

-- Policy: Users can see their own memories
create policy "Users can see their own memories"
  on memories for select
  using ( auth.uid() = user_id );

-- Policy: Users can check in memories
create policy "Users can check in memories"
  on memories for insert
  with check ( auth.uid() = user_id );

-- Policy: Users can update their own memories
create policy "Users can update their own memories"
  on memories for update
  using ( auth.uid() = user_id );

-- Policy: Users can delete their own memories
create policy "Users can delete their own memories"
  on memories for delete
  using ( auth.uid() = user_id );

-- Storage Bucket for Media
insert into storage.buckets (id, name, public)
values ('memories', 'memories', true);

-- Policy: Users can upload media to their own folder
create policy "Users can upload media"
  on storage.objects for insert
  with check ( bucket_id = 'memories' and auth.uid() = owner );
